version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - resource_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
         cd java
         mvn dependency:resolve-plugins
         mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: |
         cd java
         mvn install

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

