version: 2

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "java/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
         cd java
         mvn dependency:resolve-plugins
         mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "java/pom.xml" }}
      - run: |
         sudo apt update
         sudo apt install -y libunbound-dev libssl-dev pkg-config cmake
      - run: |
         ./build.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  deploy:
    executor: java-executor
    steps:
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "java/pom.xml" }}
          - v1-dependencies-
      - run:
          name: Deploy the artifacts
          command: |
            cd java
            mvn -s ../.circleci.settings.xml deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
               - master
