version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "java/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
         cd java
         mvn dependency:resolve-plugins
         mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "java/pom.xml" }}
      - run: |
         sudo apt update
         sudo apt install -y libunbound-dev libssl-dev pkg-config cmake
      - run: |
         ./build.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

